// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvX4uIrHh92rFA-qt7pBalBykAcOXSIWI',
    appId: '1:523750329175:web:7b75d1c8276428ecc38c12',
    messagingSenderId: '523750329175',
    projectId: 'autism-2a344',
    authDomain: 'autism-2a344.firebaseapp.com',
    storageBucket: 'autism-2a344.firebasestorage.app',
    measurementId: 'G-JX492F3RV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHrHkIZezv-Uq_a_yuFaQNtn-Zi058oDo',
    appId: '1:523750329175:android:2e4a920b4aec939ec38c12',
    messagingSenderId: '523750329175',
    projectId: 'autism-2a344',
    storageBucket: 'autism-2a344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxF50BJH3Ylo2DrVZhKOOQLySEB18bZ9I',
    appId: '1:523750329175:ios:b36a3826148e5c91c38c12',
    messagingSenderId: '523750329175',
    projectId: 'autism-2a344',
    storageBucket: 'autism-2a344.firebasestorage.app',
    iosBundleId: 'com.example.autism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxF50BJH3Ylo2DrVZhKOOQLySEB18bZ9I',
    appId: '1:523750329175:ios:b36a3826148e5c91c38c12',
    messagingSenderId: '523750329175',
    projectId: 'autism-2a344',
    storageBucket: 'autism-2a344.firebasestorage.app',
    iosBundleId: 'com.example.autism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvX4uIrHh92rFA-qt7pBalBykAcOXSIWI',
    appId: '1:523750329175:web:755fd72d5509b094c38c12',
    messagingSenderId: '523750329175',
    projectId: 'autism-2a344',
    authDomain: 'autism-2a344.firebaseapp.com',
    storageBucket: 'autism-2a344.firebasestorage.app',
    measurementId: 'G-SQZWHKMQ5H',
  );
}
